export const MOROCCAN_CITIES = [
  { fr: "Casablanca", ar: "الدار البيضاء" },
  { fr: "Rabat", ar: "الرباط" },
  { fr: "Marrakech", ar: "مراكش" },
  { fr: "Fès", ar: "فاس" },
  { fr: "Tanger", ar: "طنجة" },
  { fr: "Agadir", ar: "أكادير" },
  { fr: "Meknès", ar: "مكناس" },
  { fr: "Oujda", ar: "وجدة" },
  { fr: "Kénitra", ar: "القنيطرة" },
  { fr: "Tétouan", ar: "تطوان" },
  { fr: "Salé", ar: "سلا" },
  { fr: "Temara", ar: "تمارة" },
  { fr: "Safi", ar: "آسفي" },
  { fr: "Mohammedia", ar: "المحمدية" },
  { fr: "El Jadida", ar: "الجديدة" },
  { fr: "Béni Mellal", ar: "بني ملال" },
  { fr: "Nador", ar: "الناظور" },
  { fr: "Khouribga", ar: "خريبكة" },
  { fr: "Settat", ar: "سطات" },
  { fr: "Berrechid", ar: "برشيد" },
  { fr: "Taza", ar: "تازة" },
  { fr: "Essaouira", ar: "الصويرة" },
  { fr: "Laâyoune", ar: "العيون" },
  { fr: "Dakhla", ar: "الداخلة" },
  { fr: "Errachidia", ar: "الرشيدية" },
  { fr: "Ouarzazate", ar: "ورزازات" },
  { fr: "Al Hoceïma", ar: "الحسيمة" },
  { fr: "Larache", ar: "العرائش" },
];
